Okwedook
okwedook/HashMap pull request #6
Opened 2020-05-30 22:51 UTC by okwedook

Id посылки на ЯК: 33318788.

2020-06-09 22:22 UTC, glebshp requested changes
надо в первую очередь устранить неэффективное использование хеша

2020-06-09 22:22 UTC, glebshp commented on hash_map.h
> +* All the iterators are invalidated during
Но это же неправда, у тебя нет механизма инвалидации итераторов? То есть они становятся невалидными, но следить за этим обязан пользователь

2020-06-09 22:22 UTC, glebshp commented on hash_map.h
> +    void rehash(size_t nmd) {
сделай более развёрнутое название, чем nmd

2020-06-09 22:22 UTC, glebshp commented on hash_map.h
> +        while (c != end() && geth(c->first) == h) {
Получается, что мы для вычисления find можем использовать больше одного вычисления хеша, это очень жирно, так как часто именно вычисления хеша является узким местом по времени

2020-06-09 22:22 UTC, glebshp commented on hash_map.h
> +            if (next == end() || geth(next->first) != geth(er->first))
такая же проблема, много лишних вызовов дорогой операции - вычисления хеша

2020-06-09 22:22 UTC, glebshp commented on hash_map.h
> +        if (!count(k)) add(KeyValuePair(k, Value()));
в ситуации добавления нового элемента мы вычислим хеш от ключа целых три раза (count, add, find), а можно сделать, чтобы был один

2020-06-09 22:22 UTC, glebshp commented on hash_map.h
> +    const Value& at(const Key &k) const {
такая же проблема с лишним вычислением

2020-06-10 14:05 UTC, okwedook commented on hash_map.h
> +* All the iterators are invalidated during
Не совсем понимаю вопрос. Просто я думал это и называется инвалидацией, разве нет. Как тогда описать, что итераторы вообще говоря могут сломаться?

2020-06-19 23:36 UTC, glebshp approved these changes

2020-06-19 23:43 UTC, merged